### PR TITLE
[#73] Support GHC 9.0

### LINKED ISSUE #73: Support GHC 9.0

### PR DESCRIPTION
**Pull request by sandydoo**
Resolves #73.

Let me know if I missed anything 😄

### CODE REVIEW

**Review by vrom911 — APPROVED** [review]
Awesome, thanks so much! 🤗

**Comment by sandydoo** [comment]
Ah, https://github.com/actions/setup-haskell is unmaintained. I’ll open a PR to switch to https://github.com/haskell/actions/tree/main/setup.

Update: Done #77

**Comment by vrom911** [comment]
Awesome, thanks a lot for your thoughtful work, @sandydoo !
Now it can be rebased over the freshest `main` branch as I merged #77  👍🏼

**Comment by sandydoo** [comment]
Thanks, @vrom911! 🤗

**Pull request merged**
